// Intervals.icu sync operations
// Bulk push workouts and/or pull activities

import { NextResponse } from 'next/server'
import { createClient, createAdminClient } from '@/lib/supabase/server'
import { IntervalsICUClient, generateExternalId, formatDateForIntervals, mapSourceToPlatform } from '@/lib/intervals-icu'
import { generateZwoFromWorkout, zwoToBase64, canGenerateZwo } from '@/lib/zwo-generator'
import { SuggestedWorkout } from '@/types/training-plan'

// Type for intervals_event_links joined data (table not in generated types yet)
interface EventLink {
  id: string
  user_id: string
  suggested_workout_id: string | null
  workout_id: string | null
  intervals_event_id: string
  external_id: string
  sync_direction: 'push' | 'pull'
  scheduled_date: string
}

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const body = await request.json()
    const { action, days_forward = 14, days_back = 7 } = body

    const adminSupabase = createAdminClient()

    // Check Intervals.icu connection
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: integration, error: integrationError } = await (adminSupabase as any)
      .from('integrations')
      .select('*')
      .eq('user_id', user.id)
      .eq('provider', 'intervals_icu')
      .single()

    if (integrationError || !integration) {
      return NextResponse.json(
        { error: 'Intervals.icu not connected' },
        { status: 400 }
      )
    }

    const client = new IntervalsICUClient(adminSupabase, user.id)
    const results = {
      pushed: 0,
      pulled: 0,
      matched: 0,
      errors: [] as string[],
    }

    // Push pending workouts
    if (action === 'push_pending' || action === 'full') {
      const today = new Date()
      const endDate = new Date()
      endDate.setDate(today.getDate() + days_forward)

      // Get scheduled workouts that haven't been pushed yet
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data: scheduledWorkouts, error: workoutsError } = await (supabase as any)
        .from('suggested_workouts')
        .select('*')
        .eq('status', 'scheduled')
        .gte('suggested_date', formatDateForIntervals(today))
        .lte('suggested_date', formatDateForIntervals(endDate))

      if (workoutsError) {
        results.errors.push(`Failed to fetch workouts: ${workoutsError.message}`)
      } else if (scheduledWorkouts) {
        // Get existing links to avoid duplicates
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const { data: existingLinks } = await (adminSupabase as any)
          .from('intervals_event_links')
          .select('suggested_workout_id')
          .eq('user_id', user.id)
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          .in('suggested_workout_id', scheduledWorkouts.map((w: any) => w.id))

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const existingIds = new Set(existingLinks?.map((l: any) => l.suggested_workout_id) || [])

        // Filter to workouts that can generate ZWO and haven't been pushed
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const toPush = scheduledWorkouts.filter((w: any) =>
          !existingIds.has(w.id) && canGenerateZwo(w as SuggestedWorkout)
        )

        // Push in batches
        const batchSize = 10
        for (let i = 0; i < toPush.length; i += batchSize) {
          const batch = toPush.slice(i, i + batchSize)

          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const events = batch.map((workout: any) => {
            try {
              const sw = workout as SuggestedWorkout
              const zwoResult = generateZwoFromWorkout(sw)
              const zwoBase64 = zwoToBase64(zwoResult.xml)
              const externalId = generateExternalId(workout.id, workout.suggested_date)

              return {
                category: 'WORKOUT' as const,
                start_date_local: `${workout.suggested_date}T00:00:00`,
                name: workout.name,
                description: workout.description || 'Generated by Forge Training',
                filename: zwoResult.filename,
                file_contents: zwoBase64,
                external_id: externalId,
                color: '#F59E0B',
                _workout: workout,
                _zwo: zwoResult.xml,
              }
            } catch (err) {
              results.errors.push(`Failed to generate ZWO for ${workout.name}: ${err}`)
              return null
            }
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          }).filter((e: any): e is NonNullable<typeof e> => e !== null)

          if (events.length > 0) {
            try {
              const pushedEvents = await client.pushWorkouts(
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                events.map(({ _workout, _zwo, ...e }: any) => e)
              )

              // Store links
              for (let j = 0; j < pushedEvents.length; j++) {
                const event = events[j]
                const pushed = pushedEvents[j]

                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                await (adminSupabase as any)
                  .from('intervals_event_links')
                  .upsert({
                    user_id: user.id,
                    suggested_workout_id: event._workout.id,
                    workout_id: event._workout.scheduled_workout_id || null,
                    intervals_event_id: pushed.id.toString(),
                    external_id: event.external_id,
                    sync_direction: 'push',
                    zwo_content: event._zwo,
                    scheduled_date: event._workout.suggested_date,
                    synced_at: new Date().toISOString(),
                    last_sync_status: 'success',
                  }, {
                    onConflict: 'external_id',
                  })

                results.pushed++
              }
            } catch (err) {
              results.errors.push(`Batch push failed: ${err}`)
            }
          }
        }
      }
    }

    // Pull completed activities
    if (action === 'pull_activities' || action === 'full') {
      const today = new Date()
      const startDate = new Date()
      startDate.setDate(today.getDate() - days_back)

      try {
        const activities = await client.getActivities(
          formatDateForIntervals(startDate),
          formatDateForIntervals(today)
        )

        // Get our pushed events to match against
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const { data: eventLinks } = await (adminSupabase as any)
          .from('intervals_event_links')
          .select('*, suggested_workouts(*), workouts(*)')
          .eq('user_id', user.id)
          .eq('sync_direction', 'push')
          .gte('scheduled_date', formatDateForIntervals(startDate))

        const linksByExternalId = new Map<string, EventLink>(
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          eventLinks?.map((l: any) => [l.external_id, l] as [string, EventLink]) || []
        )

        for (const activity of activities) {
          // Try to match by external_id (if the completed activity originated from our workout)
          const matchedLink: EventLink | null = activity.external_id
            ? linksByExternalId.get(activity.external_id) || null
            : null

          if (matchedLink && matchedLink.workout_id) {
            // Update the workout with actual metrics
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            await (adminSupabase as any)
              .from('workouts')
              .update({
                status: 'completed',
                completed_at: activity.start_date_local,
                actual_duration_minutes: Math.round(activity.moving_time / 60),
                actual_avg_power: activity.average_watts,
                actual_np: activity.icu_weighted_avg_watts,
                actual_avg_hr: activity.average_heartrate,
                actual_max_hr: activity.max_heartrate,
                actual_tss: activity.icu_training_load,
                training_load: activity.icu_training_load,
                external_id: activity.id,
                updated_at: new Date().toISOString(),
              })
              .eq('id', matchedLink.workout_id)

            // Update suggested workout status
            if (matchedLink.suggested_workout_id) {
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              await (adminSupabase as any)
                .from('suggested_workouts')
                .update({ status: 'scheduled' })  // Keep as scheduled, workout is completed
                .eq('id', matchedLink.suggested_workout_id)
            }

            // Create RPE prompt
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const { data: profile } = await (adminSupabase as any)
              .from('profiles')
              .select('rpe_prompt_delay_minutes')
              .eq('id', user.id)
              .single()

            const promptDelay = profile?.rpe_prompt_delay_minutes || 30
            const scheduledFor = new Date(activity.start_date_local)
            scheduledFor.setMinutes(scheduledFor.getMinutes() + (activity.moving_time / 60) + promptDelay)

            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            await (adminSupabase as any)
              .from('rpe_prompts')
              .upsert({
                user_id: user.id,
                workout_id: matchedLink.workout_id,
                suggested_workout_id: matchedLink.suggested_workout_id,
                intervals_activity_id: activity.id,
                source_platform: mapSourceToPlatform(activity.source),
                prompt_type: 'both',
                scheduled_for: scheduledFor.toISOString(),
              }, {
                onConflict: 'workout_id',
              })

            results.matched++
          }

          results.pulled++
        }
      } catch (err) {
        results.errors.push(`Failed to pull activities: ${err}`)
      }
    }

    // Update last poll timestamp
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (adminSupabase as any)
      .from('integrations')
      .update({
        last_poll_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq('id', integration.id)

    return NextResponse.json(results)

  } catch (error) {
    console.error('Intervals.icu sync error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Sync failed' },
      { status: 500 }
    )
  }
}
