// Push workout to Intervals.icu
// Converts workout to ZWO format and uploads to Intervals.icu calendar

import { NextResponse } from 'next/server'
import { createClient, createAdminClient } from '@/lib/supabase/server'
import { IntervalsICUClient, generateExternalId } from '@/lib/intervals-icu'
import { generateZwoFromWorkout, zwoToBase64, canGenerateZwo } from '@/lib/zwo-generator'
import { SuggestedWorkout } from '@/types/training-plan'

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const body = await request.json()
    const { suggested_workout_id, workout_id } = body

    if (!suggested_workout_id && !workout_id) {
      return NextResponse.json(
        { error: 'Either suggested_workout_id or workout_id is required' },
        { status: 400 }
      )
    }

    const adminSupabase = createAdminClient()

    // Check if user has Intervals.icu connected
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: integration, error: integrationError } = await (adminSupabase as any)
      .from('integrations')
      .select('*')
      .eq('user_id', user.id)
      .eq('provider', 'intervals_icu')
      .single()

    if (integrationError || !integration) {
      return NextResponse.json(
        { error: 'Intervals.icu not connected' },
        { status: 400 }
      )
    }

    // Fetch the workout data
    let workout: SuggestedWorkout | null = null
    let scheduledDate: string | null = null

    if (suggested_workout_id) {
      const { data, error } = await supabase
        .from('suggested_workouts')
        .select('*')
        .eq('id', suggested_workout_id)
        .single()

      if (error || !data) {
        return NextResponse.json({ error: 'Workout not found' }, { status: 404 })
      }

      workout = data as SuggestedWorkout
      scheduledDate = workout.suggested_date
    } else if (workout_id) {
      // Fetch from workouts table and convert to suggested workout format
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data, error } = await (supabase as any)
        .from('workouts')
        .select('*')
        .eq('id', workout_id)
        .single()

      if (error || !data) {
        return NextResponse.json({ error: 'Workout not found' }, { status: 404 })
      }

      // Check if this workout has an associated suggested workout with cardio structure
      const { data: suggestedData } = await supabase
        .from('suggested_workouts')
        .select('*')
        .eq('scheduled_workout_id', workout_id)
        .single()

      if (suggestedData) {
        workout = suggestedData as SuggestedWorkout
      } else {
        // Create a minimal suggested workout from the actual workout
        workout = {
          id: data.id,
          name: data.name,
          description: data.description,
          category: data.category || 'cardio',
          workout_type: data.workout_type || 'bike',
          cardio_structure: data.cardio_structure || null,
          planned_duration_minutes: data.planned_duration_minutes,
          primary_intensity: data.planned_intensity as any,
        } as any
      }

      scheduledDate = data.scheduled_date
    }

    if (!workout) {
      return NextResponse.json({ error: 'Workout not found' }, { status: 404 })
    }

    // Check if workout can generate ZWO
    if (!canGenerateZwo(workout)) {
      return NextResponse.json(
        { error: 'Workout does not have valid cardio structure for ZWO generation' },
        { status: 400 }
      )
    }

    // Generate ZWO
    const zwoResult = generateZwoFromWorkout(workout)
    const zwoBase64 = zwoToBase64(zwoResult.xml)
    const externalId = generateExternalId(workout.id, scheduledDate || undefined)

    // Push to Intervals.icu
    const client = new IntervalsICUClient(adminSupabase, user.id)

    const event = await client.pushWorkout({
      category: 'WORKOUT',
      start_date_local: `${scheduledDate}T00:00:00`,
      name: workout.name,
      description: workout.description || `Generated by Forge Training`,
      filename: zwoResult.filename,
      file_contents: zwoBase64,
      external_id: externalId,
      color: '#F59E0B',  // Forge amber
    })

    // Store the link in our database
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (adminSupabase as any)
      .from('intervals_event_links')
      .upsert({
        user_id: user.id,
        suggested_workout_id: suggested_workout_id || null,
        workout_id: workout_id || null,
        intervals_event_id: event.id.toString(),
        external_id: externalId,
        sync_direction: 'push',
        zwo_content: zwoResult.xml,
        scheduled_date: scheduledDate,
        synced_at: new Date().toISOString(),
        last_sync_status: 'success',
      }, {
        onConflict: 'external_id',
      })

    return NextResponse.json({
      success: true,
      intervals_event_id: event.id,
      external_id: externalId,
      filename: zwoResult.filename,
      duration_minutes: zwoResult.totalDurationMinutes,
    })

  } catch (error) {
    console.error('Failed to push workout to Intervals.icu:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to push workout' },
      { status: 500 }
    )
  }
}
